# Data generation parameters
rng_seed: 42 # random seed
n_repits: 10 # number of repetitions
n_train_points: 40000 # number of training samples
n_val_points: 1000 # number of validation samples
n_test_points: 1000 # number of test samples

# Experiment parameters
delta: 0.05 # confidence level

# plot parameters
n_plot_tau: 10000 # number of points to plot bounds versus tau

# Model parameters
rank: 3 # rank of the reduced ranks model
lamda: 0.0001 # Tikhonov regularization parameter
reduced_rank: True 

