# Data generation parameters
rng_seed: 42 # random seed
n_repits: 30 # number of repetitions
n_train_points: 40000 # number of training samples
n_val_points: 0 # number of validation samples
n_test_points: 0 # number of test samples

# Experiment parameters
delta: 0.05 # confidence level
n_sample_est_tr: 20000
n_repits_est_tr: 100
n_train_first: 500

n_sample_thresh: 10000

# plot parameters
n_plot_tau: 20000 # number of points to plot bounds versus tau

# Model parameters
rank: 3 # rank of the reduced ranks model
tikhonov_reg: 0.0001 # Tikhonov regularization parameter

