encoder_kwargs:
  configs: !!python/object:abc.LoadedConfigs
    _is_jax_pytree: false
    _storage:
      classes: 5
      conv1_kernel_size: 5
      conv1_out_channels: 16
      conv1_padding: 2
      conv1_stride: 1
      conv2_kernel_size: 5
      conv2_out_channels: 32
      conv2_padding: 2
      conv2_stride: 1
      delta: 0.05
      dpnet_batch_size: 64
      dpnet_center_covariances: false
      dpnet_lr: 0.0009
      dpnet_max_epochs: 50
      dpnet_metric_deformation: 1
      dpnet_relaxed: false
      eta: 0.05
      eval_up_to_t: 15
      fc_input_size: 1568
      maxpool1_kernel_size: 2
      maxpool2_kernel_size: 2
      n_repits: 10
      oracle_batch_size: 64
      oracle_epochs: 20
      oracle_lr: 0.01
      reduced_rank: true
      rng_seed: 42
      test_samples: 1001
      train_samples: 1001
      val_ratio: 0.2
    classes: 5
    conv1_kernel_size: 5
    conv1_out_channels: 16
    conv1_padding: 2
    conv1_stride: 1
    conv2_kernel_size: 5
    conv2_out_channels: 32
    conv2_padding: 2
    conv2_stride: 1
    delta: 0.05
    dpnet_batch_size: 64
    dpnet_center_covariances: false
    dpnet_lr: 0.0009
    dpnet_max_epochs: 50
    dpnet_metric_deformation: 1
    dpnet_relaxed: false
    eta: 0.05
    eval_up_to_t: 15
    fc_input_size: 1568
    maxpool1_kernel_size: 2
    maxpool2_kernel_size: 2
    n_repits: 10
    oracle_batch_size: 64
    oracle_epochs: 20
    oracle_lr: 0.01
    reduced_rank: true
    rng_seed: 42
    test_samples: 1001
    train_samples: 1001
    val_ratio: 0.2
  num_classes: 5
lagged_encoder_kwargs: {}
loss_kwargs:
  center_covariances: false
  metric_deformation: 1
  relaxed: false
optimizer_kwargs:
  lr: 0.0009
