# Data generation parameters
rng_seed: 42 # random seed
eta: 0.2 # noise level
classes: 5 # number of classes
train_samples: 10001 # number of training samples
test_samples: 1001 # number of test samples
val_ratio: 0.2 # validation ratio

# experiment parameters
delta: 0.05 # confidence level
n_repits: 10 # number of repetitions
n_train_first: 500 # number of training samples in the first step 
n_train_step: 500 # number of training samples in each step

# plot parameters
eval_up_to_t: 15 # number of steps to forecast
test_seed_idx: 0 # index of the test seed for the plot
n_train_acc_plot: 1 # number of training samples to plot the accuracy
n_rep_plot: 0 # The repetition to plot the accuracy

# Model parameters
reduced_rank: True 
dpnet_max_epochs: 50
dpnet_lr: 0.0009 
dpnet_metric_deformation: 1
dpnet_center_covariances: False
dpnet_relaxed: False
dpnet_batch_size: 64

# Oracle parameters
oracle_input_size1: 28
oracle_input_size2: 28
conv1_in_channels: 1
conv1_out_channels: 16
conv1_kernel_size: 5
conv1_stride: 1
conv1_padding: 2

maxpool1_kernel_size: 2

conv2_out_channels: 32
conv2_kernel_size: 5
conv2_stride: 1
conv2_padding: 2

maxpool2_kernel_size: 2

fc_input_size: 1568 # 32 * 7 * 7

oracle_epochs: 20
oracle_lr: 0.01
oracle_batch_size: 64
